Fix for issue #143
fastai/fastcore pull request #146
Opened 2020-10-23 22:01 UTC by Salehbigdeli

See my comment on issue #143

2020-10-24 00:23 UTC, Salehbigdeli commented
More detail on these changes can be found in issue #147

2020-10-24 00:36 UTC, Salehbigdeli commented
I don't know if I broke something in plots! Since we don't have anything to check plots automatically, here is screenshot of cell that made last pipeline execution fail:

![image](https://user-images.githubusercontent.com/34204311/97063602-7ddb9480-15ad-11eb-8090-2517c583fbfe.png)

2020-10-26 07:56 UTC, hal-314 requested changes

2020-10-26 07:56 UTC, hal-314 commented on fastcore/foundation.py
> +    if hasattr(x,'__array__') or hasattr(x,'iloc'): return bool(x.shape)
I think that you broke things as you return `None` is it doesn't enter in the `if`. So, you could rewrite as:
```
def _is_array(x):
    # First, check if it could be an array (np.array or pandas Dataframe/Serie and then check that has shape. If it doesn't , it's a constant value. 
    return (hasattr(x,'__array__') or hasattr(x,'iloc')) and bool(x.shape)
```

2020-10-30 13:15 UTC, jph00 requested changes
I think the piece where you are using numpy needs more thought, and maybe some tests/examples. When exactly would you end up in that part of the conditional? Would it always be true, or always false? What do you need to check for, really?

2020-10-30 13:15 UTC, jph00 commented on fastcore/foundation.py
> +        import numpy as np
We can't introduce a dep on numpy into fastcore. fastcore is designed to be lightweight with no deps outside the standard lib.

2020-10-30 13:15 UTC, jph00 commented on fastcore/foundation.py
> +    "First, check if it could be an array (np.array or pandas Dataframe/Serie and then check that has shape. If it doesn't , it's a constant value."
The "First, " here is confusing. I'd suggest removing it

2020-10-30 13:23 UTC, Salehbigdeli commented on fastcore/foundation.py
> +    "First, check if it could be an array (np.array or pandas Dataframe/Serie and then check that has shape. If it doesn't , it's a constant value."
Ok, I'll remove it.

2020-10-30 17:59 UTC, Salehbigdeli commented on fastcore/foundation.py
> +        import numpy as np
Tabular class doesn't have `shape` attribute. So I decided to add `shape` to `CollBase`. After that there was a situation in which `items` of a Collection doesn't have `shape` attribute (like `lists`).
I changed the code so that it doesn't use `numpy` anymore. But unfortunately, I couldn't merge the code locally and continue with this pull request! and I created a new pull request!

2020-11-13 13:37 UTC, jph00 commented
Seems like this is obsolete now. Please close obsolete PRs in the future @Salehbigdeli, since it helps keep things clean! :) If for any reason you do need to create a new PR instead of updating an existing one, be sure to reference the old closed PR from the new one.

2020-11-13 13:37 UTC, closed without merging