Pr146
fastai/fastcore pull request #159
Opened 2020-10-30 17:52 UTC by Salehbigdeli

2020-10-30 19:07 UTC, tcapelle commented
Add shape to L?

2020-10-30 19:09 UTC, Salehbigdeli commented
> Add shape to L?

Add `shape` to everything that inherits from `CollBase`

2020-11-10 09:07 UTC, hamelsmu commented
@Salehbigdeli this PR has conflicts, mind fixing this?

2020-11-12 17:34 UTC, Salehbigdeli commented
> @Salehbigdeli this PR has conflicts, mind fixing this?

I don't have write access!

2020-11-12 18:51 UTC, hamelsmu commented
You don't need write access

2020-11-12 19:18 UTC, Salehbigdeli commented
Unfortunately, I don't know how! Should I create another PR?

2020-11-13 13:30 UTC, jph00 commented
Thanks @Salehbigdeli . To fix your conflicts, first checkout the branch you made the PR in, fix the conflict, then push your branch back to your fork. That will update this PR.

https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo

2020-11-13 13:33 UTC, jph00 requested changes
A couple of requests. Also, please put a description of your change in the title or the PR and information about what it does in the description. Include "fixes #..." in the PR description, not just the commit messages.

2020-11-13 13:33 UTC, jph00 commented on fastcore/foundation.py
> +    return (hasattr(x,'__array__') or hasattr(x,'iloc')) and bool(x.shape)
I don't think you need `bool()` do you?

2020-11-13 13:33 UTC, jph00 commented on fastcore/foundation.py
> +    @property
Not all collections have a shape, since they might have jagged shapes. Also, adding a core property like this to such a basic structure is quite likely to break a lot of downstream code.

Instead, fix just the class where you saw the problem, in the most direct and simple way.

2020-11-13 16:48 UTC, Salehbigdeli commented
> Thanks @Salehbigdeli . To fix your conflicts, first checkout the branch you made the PR in, fix the conflict, then push your branch back to your fork. That will update this PR.
> 
> https://stackoverflow.com/questions/9790448/how-to-update-a-pull-request-from-forked-repo

Thanks

2020-11-13 16:49 UTC, Salehbigdeli commented
I close this PR since the original issue is resolved

2020-11-13 16:49 UTC, closed without merging