Fixes #256
fastai/fastcore pull request #257
Opened 2020-12-16 23:59 UTC by dansbecker

I believe the desired behavior if a user doesn't have fast_progress installed is to continue with no progress bar rather than to throw an exception... though a warning would also be reasonable.

Here's a patch that continues without the progress bar in that case.

2020-12-19 03:35 UTC, hamelsmu commented
Hi @dansbecker you have to actually edit the corresponding notebook in order to change this code.  I'm happy to pair with you if you are interested!  So nice to see you here! ❤️ 

cc: look@jph00 its our friend, @dansbecker !!!

2020-12-20 13:54 UTC, dansbecker commented
@hamelsmu Ah... I assume I am supposed to make the change [here](https://github.com/fastai/fastcore/blob/master/nbs/03a_parallel.ipynb) and not directly in the .py file?

I'm excited for any excuse to catch up, but I have a hunch this change will be a 1-minute change when we pair up.

2020-12-21 18:07 UTC, jph00 requested changes
Thanks @dansbecker . If you just run `nbdev_build_lib` now it should be good to go!

2020-12-21 18:29 UTC, dansbecker commented
Thanks @jph00. 

Your comment caused me to look at nbdev a little more... it's cool to see what's happening here.

2020-12-21 18:31 UTC, jph00 commented
Thanks @dansbecker - you might be interested in this video:
https://www.youtube.com/watch?v=9Q6sLbz37gk

2020-12-21 18:31 UTC, merged