adds mkdir
fastai/fastcore pull request #427
Opened 2022-07-08 10:19 UTC by lgvaz

Adds `mkdir` function as described in discord [here](https://discord.com/channels/689892369998676007/689892370002870284/993544265093357749).

I feel like my tests might be a bit convoluted? Please feel free to suggest changes :)

2022-07-08 10:24 UTC, lgvaz commented
Hmm, some permission error on the CI

2022-07-09 00:05 UTC, jph00 commented
Yeah you can't delete a directory you're using in Windows. And your `with` block means you're using it.

Change your code so you don't use `with`, but instead use a `finally` block to clean up.

(PS: be sure to at-mention me on PRs so I see them)

2022-07-09 06:23 UTC, lgvaz commented
Heh @jph00, I don't know how to do this 😅

2022-07-09 07:15 UTC, jph00 commented
Hey no worries. You're still using a `with` block for the directory. Your commit only changed the file.

2022-07-09 07:16 UTC, jph00 commented
Feel free to close the PR if you don't feel like debugging this -- it's not a big deal either way :)

2022-07-09 08:05 UTC, lgvaz commented
No no, don't get me wrong, I really wanna do this, I just had spent and hour trying to understand the error and was not getting nowhere so I asked for help, but in hindsight "I don't know how to do this" is one of the worse ways for asking help, sorry about that.

Anyways, the directory is using `with`!!! I completely overlooked that and tunel visioned on the file, I'll try it again now :)

2022-07-09 08:29 UTC, jph00 commented
Message ID: ***@***.***>No apologies required! - Just didn't want you to feel any pressure :)

2022-07-09 09:21 UTC, lgvaz commented
Yeeeee @jph00 had to be a bit hacky but it worked! I had to manually close the file and the directory for windows to be happy about deleting it hahahah. Let me know if you think there's a better way to do this, maybe again I just focused too much into using the temporary dir/files and missed an simpler approach.

Btw, should I tag you in every update in the PR or just once at the beggining?

2022-07-09 09:31 UTC, jph00 commented
This is using a private method, which isn't a good idea.

I think you're making this over complicated frankly. There are examples on stack overflow that'll show you how to get a temporary file name without actually creating anything. Afaict you should be fine to use "with" for the file, just not for the directory.

You only need to tag me at the start of a PR

2022-07-22 10:25 UTC, lgvaz commented
Hi! Just want to say I have not forgotten about this. I just got my hands on a windows laptop so that will make it much easier to figure this out!

2022-08-17 11:27 UTC, lgvaz commented
Hi Jeremy! It's been a while but I finally figured it out. As you suggested, I was overcomplicating: I don't need to create a temporary file inside a temporary directory, I can just create a normal file!!

The CI on windows is currently disabled, but I tested this on a windows machine and it works!

2022-08-17 17:02 UTC, jph00 requested changes
Looking very close now!

2022-08-17 17:02 UTC, jph00 commented on nbs/.gitattributes
> -*.ipynb merge=nbdev-merge
Can you revert your change to this file please? Looks like you've got an old version of nbdev hooks installed that's created this change.

2022-08-17 17:02 UTC, jph00 commented on nbs/03_xtras.ipynb
> +    "    path = Path(path)\n",
You should add `import shutil` here. Currently this import is only in a non-exported cell, so this won't work outside this notebook.

2022-08-18 07:40 UTC, lgvaz commented on nbs/.gitattributes
> -*.ipynb merge=nbdev-merge
done :)

2022-08-18 07:41 UTC, lgvaz commented on nbs/03_xtras.ipynb
> +    "    path = Path(path)\n",
done! it should be inside the function right?

2022-08-18 07:46 UTC, lgvaz commented
I see there's a conflict now. Is it because the cell number of my added function has changed compared to master?

2022-08-18 10:47 UTC, jph00 commented
Message ID: ***@***.***>It could be - if you just pull the latest changes and let them overwrite your .py file, you can the export again.

2022-08-19 07:10 UTC, lgvaz commented
Done! :)

2022-08-19 10:29 UTC, jph00 commented
Good stuff!

2022-08-19 10:30 UTC, merged