enable meta.delegates to enforce KEYWORD_ONLY for kwargs from
fastai/fastcore pull request #459
Opened 2022-08-08 08:42 UTC by EmbraceLife

The details of this PR can be found in this forum [thread](https://forums.fast.ai/t/python-help/97525/22?u=daniel).

2022-08-10 17:15 UTC, jph00 requested changes
Many thanks for the PR. I've made one suggested change (but haven't tested it -- so take a look and see if it works for you!).

You've accidentally added the whole _docs directory to your PR. Could you please remove it? I've just updated .gitignore so that this shouldn't happen again in the future.

2022-08-10 17:15 UTC, jph00 commented on fastcore/meta.py
>          s2 = {k:v for k,v in inspect.signature(to_f).parameters.items()
```suggestion
        s2 = {k:v.replace(kind=inspect.Parameter.KEYWORD_ONLY) for k,v in inspect.signature(to_f).parameters.items()
```

If you made this change, would that mean you could then remove the line you added?

2022-08-10 23:40 UTC, EmbraceLife commented on fastcore/meta.py
>          s2 = {k:v for k,v in inspect.signature(to_f).parameters.items()
Yes, this change works and my added line can be removed. Thanks Jeremy!

2022-08-10 23:44 UTC, jph00 commented on fastcore/meta.py
>          s2 = {k:v for k,v in inspect.signature(to_f).parameters.items()
Great. Just reply here when you've removed the `_docs` folder and we should be ready to go!

2022-08-10 23:44 UTC, EmbraceLife commented
I have reverted my first troublesome commit and then only run `nbdev_prepare` this time without running all the cells, nor running `nbdev_docs` and `nbdev_preview`, so that I didn't generate so many differences.

2022-08-10 23:49 UTC, jph00 commented
Good job!

2022-08-11 00:01 UTC, merged

2022-08-11 02:12 UTC, EmbraceLife commented
<p>Thank you Jeremy! This is my first contribution to fastcore, Wow!</p>