add body to error message
fastai/fastcore pull request #480
Opened 2022-09-05 19:38 UTC by hamelsmu

Closes #479

2022-09-05 22:25 UTC, jph00 requested changes

2022-09-05 22:25 UTC, jph00 commented on fastcore/net.py
> +    except Exception as e: raise e
I think you can remove this line

2022-09-05 22:25 UTC, jph00 commented on fastcore/net.py
> +        raise e
Should there be a "from None" or something at the end here to avoid a complex stack trace?

2022-09-05 22:25 UTC, jph00 commented on fastcore/net.py
> +        e.msg += f"\n====Error Body====\n{pformat(json.loads(e.read()))}"
The error won't always be json will it?

2022-09-05 22:25 UTC, jph00 commented on fastcore/net.py
>          else: raise
Actually maybe this line isn't needed either?

2022-09-06 00:47 UTC, hamelsmu commented on fastcore/net.py
>          else: raise
I think that is still needed?  What if the the code is not betwen 400 and 500?

2022-09-06 01:01 UTC, hamelsmu commented on fastcore/net.py
> +        e.msg += f"\n====Error Body====\n{pformat(json.loads(e.read()))}"
good catch

2022-09-06 02:23 UTC, hamelsmu commented on fastcore/net.py
> +        raise e
Decided that `from None` doesn't do anything here, but changed it to just `raise` instead of `raise e`

2022-09-06 02:24 UTC, hamelsmu commented on fastcore/net.py
> +    except Exception as e: raise e
good point

2022-09-06 02:25 UTC, hamelsmu commented
@jph00 thanks for the review.  You can take a look when you are ready again, I've made changes as discussed

2022-09-06 05:54 UTC, jph00 commented on fastcore/net.py
>          else: raise
Oh right yeah I misread the indentation.

2022-09-06 05:55 UTC, merged